version: "3.9"

services:
  # Service API — l'application principale
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: sonar-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped

  # Service trainer — entraîne le modèle et s'arrête
  trainer:
    build:
      context: .
      dockerfile: Dockerfile
      target: trainer
    container_name: sonar-trainer
    volumes:
      - ./models:/app/models
